# Basic Site Settings
locale                   : "en-US"
site_theme               : "air" # Currently available options are "default", "air"
title                    : "ERHUER / RESEARCH LIFE OF PRE PHD!"
title_separator          : "-"
name                     : &name "Xinlong Hu"
description              : &description "Undergraduate of Xizang University, pre doctoral student of the nssc"   
url                      : https://erhuer.github.io # The base hostname & protocol for your site e.g. "https://[your GitHub username].github.io",
                                                           # or if you already have some other page hosted on Github then use "https://[your GitHub username].github.io/[Your Repo Name]"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "academicpages/academicpages.github.io"

# Site Author - The following control what appear as part of the author content on the side bar.
#               If a field is blank the icon and link will not appear, otherwise it will be shown.
#               Additional customization can be done by editing /_includes/author-profile.html
author:
  # Biographic information
  avatar           : "profile.png"
  name             : "Xinlong Hu"
  pronouns         : "he/him"  
  bio              : "XiZang University"
  location         : "China BEIJING"
  employer         : "Lei Dai"
  uri              : "https://erhuer.github.io"
  email            : "erhuer@stu.utibet.edu.cn" 

  # Academic websites
  academia         : 
  arxiv            : 
  googlescholar    : 
  inspire-hep      : 
  impactstory      : 
  orcid            : "http://orcid.org/0009-0008-8827-4212"
  semantic         : 
  pubmed           : "https://www.ncbi.nlm.nih.gov/pubmed/?term=john+snow"
  researchgate     : 
  scopus           : 

  # Repositories and software development
  bitbucket        : # Username - Update with your username on the site
  codepen          : # Username
  dribbble         : # Username
  github           : "https://github.com/erhuer"
  kaggle           : # Username  
  stackoverflow    : # User number or user number and name (i.e., use "1" or "1/jeff-atwood")    

  # Social media
  artstation       : # Username
  bluesky          : "bsky.app" # Replace this with you Bluesky username
  facebook         : # Username
  flickr           : # Username
  foursquare       : # Username
  goodreads        : # Username
  google_plus      : # Username
  keybase          : # Username
  instagram        : # Username
  lastfm           : # Username
  linkedin         : # Username
  mastodon         : # URL
  medium           : # URL
  pinterest        : # Username
  soundcloud       : # Username
  steam            : # Username
  telegram         : # URL
  tumblr           : # Username
  twitter          : # Username for X / Twitter
  vine             : # Username
  weibo            : # Username
  wikipedia        : # Username
  xing             : # Username
  youtube          : # Username
  zhihu            : # Username

# Publication Category - The following the list of publication categories and their headings
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'    
  conferences:
    title: 'Conference Papers'
